services:
  pgdb:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - kittydb:/var/lib/postgresql/data

volumes:
  kittydb:
